CREATE TABLE comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES posts(id) ON DELETE CASCADE,
  author text,
  content text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX comments_post_id_idx ON comments (post_id);
CREATE INDEX comments_created_at_idx ON comments (created_at DESC);
